package com.camille.mybatis.pojo;

import java.io.Serializable;

public class Dept implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.department_id
     *
     * @mbggenerated Mon Feb 28 17:31:50 CST 2022
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.department_name
     *
     * @mbggenerated Mon Feb 28 17:31:50 CST 2022
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.department_id
     *
     * @return the value of t_dept.department_id
     *
     * @mbggenerated Mon Feb 28 17:31:50 CST 2022
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.department_id
     *
     * @param departmentId the value for t_dept.department_id
     *
     * @mbggenerated Mon Feb 28 17:31:50 CST 2022
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.department_name
     *
     * @return the value of t_dept.department_name
     *
     * @mbggenerated Mon Feb 28 17:31:50 CST 2022
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.department_name
     *
     * @param departmentName the value for t_dept.department_name
     *
     * @mbggenerated Mon Feb 28 17:31:50 CST 2022
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    @Override
    public String toString() {
        return "Dept{" +
                "departmentId=" + departmentId +
                ", departmentName='" + departmentName + '\'' +
                '}';
    }
}